system_controllers:
    resource:
        path: ../src/System/UI/Http/Controller/
        namespace: App\System\UI\Http\Controller
    type: attribute
    prefix: /api

machine_controllers:
    resource:
        path: ../src/VendingMachine/Machine/UI/Http/Controller/
        namespace: App\VendingMachine\Machine\UI\Http\Controller
    type: attribute
    prefix: /api

admin_controllers:
    resource:
        path: ../src/AdminPanel/User/UI/Http/Controller/
        namespace: App\AdminPanel\User\UI\Http\Controller
    type: attribute
    prefix: /api/admin

admin_coin_controllers:
    resource:
        path: ../src/AdminPanel/Coin/UI/Http/Controller/
        namespace: App\AdminPanel\Coin\UI\Http\Controller
    type: attribute
    prefix: /api/admin

admin_inventory_controllers:
    resource:
        path: ../src/AdminPanel/Inventory/UI/Http/Controller/
        namespace: App\AdminPanel\Inventory\UI\Http\Controller
    type: attribute
    prefix: /api/admin
