shared_controllers:
    resource:
        path: ../src/Shared/UI/Http/Controller/
        namespace: App\Shared\UI\Http\Controller
    type: attribute

vending_controllers:
    resource:
        path: ../src/VendingMachine/UI/Http/Controller/
        namespace: App\VendingMachine\UI\Http\Controller
    type: attribute
    prefix: /api

admin_controllers:
    resource:
        path: ../src/AdminPanel/UI/Http/Controller/
        namespace: App\AdminPanel\UI\Http\Controller
    type: attribute
    prefix: /api/admin
