system_controllers:
    resource:
        path: ../src/System/UI/Http/Controller/
        namespace: App\System\UI\Http\Controller
    type: attribute

vending_controllers:
    resource:
        path: ../src/VendingMachine/Product/UI/Http/Controller/
        namespace: App\VendingMachine\Product\UI\Http\Controller
    type: attribute
    prefix: /api

admin_controllers:
    resource:
        path: ../src/AdminPanel/User/UI/Http/Controller/
        namespace: App\AdminPanel\User\UI\Http\Controller
    type: attribute
    prefix: /api/admin
