# This file configures your own services.

parameters:
    app.project_dir: '%kernel.project_dir%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/AdminPanel/Domain/'
            - '../src/AdminPanel/Application/DTO/'
            - '../src/VendingMachine/Domain/'
            - '../src/VendingMachine/Application/DTO/'
            - '../src/Shared/Domain/'
            - '../src/Shared/Application/DTO/'
            - '../src/AdminPanel/Infrastructure/User/Document/'
            - '../src/AdminPanel/UI/Http/Security/'
            - '../src/Kernel.php'

    App\AdminPanel\Infrastructure\User\Document\:
        resource: '../src/AdminPanel/Infrastructure/User/Document/'
        public: false
