# This file configures your own services.

parameters:
    app.project_dir: '%kernel.project_dir%'
    app.machine_id: 'vendingmachine-default'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/AdminPanel/User/Domain/'
            - '../src/AdminPanel/Application/DTO/'
            - '../src/VendingMachine/Product/Domain/'
            - '../src/VendingMachine/Application/DTO/'
            - '../src/Shared/Money/Domain/'
            - '../src/Shared/Application/DTO/'
            - '../src/Kernel.php'

    App\AdminPanel\User\Domain\AdminUserRepository: '@App\AdminPanel\User\Infrastructure\Mongo\MongoAdminUserRepository'

    App\AdminPanel\User\Application\Security\AdminAccessTokenGenerator: '@App\AdminPanel\User\Infrastructure\Token\JwtAdminTokenService'

    App\AdminPanel\User\Application\Security\AdminAccessTokenValidator: '@App\AdminPanel\User\Infrastructure\Token\JwtAdminTokenService'

    App\AdminPanel\User\Infrastructure\Token\JwtAdminTokenService:
        arguments:
            $secret: '%env(ADMIN_JWT_SECRET)%'
            $ttlInSeconds: '%env(int:ADMIN_JWT_TTL)%'
            $issuer: '%env(string:ADMIN_JWT_ISSUER)%'

    App\VendingMachine\Machine\Application\Service\MongoMachineStateProvider:
        arguments:
            $machineId: '%app.machine_id%'

    App\VendingMachine\Machine\Application\Service\MachineStateProvider: '@App\VendingMachine\Machine\Application\Service\MongoMachineStateProvider'

    App\VendingMachine\Machine\Infrastructure\Command\SeedMachineStateCommand:
        arguments:
            $machineId: '%app.machine_id%'
