# This file configures your own services.

parameters:
    app.project_dir: '%kernel.project_dir%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/AdminPanel/User/Domain/'
            - '../src/AdminPanel/Application/DTO/'
            - '../src/VendingMachine/Product/Domain/'
            - '../src/VendingMachine/Application/DTO/'
            - '../src/Shared/Money/Domain/'
            - '../src/Shared/Application/DTO/'
            - '../src/AdminPanel/User/Infrastructure/User/Document/'
            - '../src/AdminPanel/User/UI/Http/Security/'
            - '../src/Kernel.php'

    App\AdminPanel\User\Infrastructure\User\Document\:
        resource: '../src/AdminPanel/User/Infrastructure/User/Document/'
        public: false
