doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    default_connection: default
    default_database: '%env(resolve:MONGO_DATABASE)%'
    connections:
        default:
            server: '%env(resolve:MONGO_DSN)%'
            options: { }
    document_managers:
        default:
            auto_mapping: false
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src'
                    prefix: 'App'
                    alias: App
