framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\\Application\\Message\\': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
