name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  tests:
    name: PHP Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mongodb
          coverage: none
          tools: composer
          ini-values: memory_limit=-1
          cache: composer

      - name: Prepare environment file
        run: |
          if [ -f .env.dist ]; then
            cp .env.dist .env
          elif [ -f ../.env.dist ]; then
            cp ../.env.dist .env
          else
            echo "No .env.dist template found" >&2
            exit 1
          fi
          if ! grep -q '^DEFAULT_URI=' .env; then
            echo 'DEFAULT_URI=http://localhost' >> .env
          fi
          if ! grep -q '^APP_ENV=' .env; then
            echo 'APP_ENV=test' >> .env
          else
            perl -0pi -e 's/^APP_ENV=.*$/APP_ENV=test/m' .env
          fi

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run code style check
        run: composer run lint

      - name: Run static analysis
        run: composer run phpstan

      - name: Run PHPUnit
        env:
          APP_ENV: test
          APP_DEBUG: 0
        run: composer run test
